### ISSUE TITLE
Use relative paths for standards install paths.

### ISSUE THREAD

**Issue by Decipher** [alexdesignworks/dcr#28]
Currently, during `register_codesniffer_standards`, install paths for standards use absolute paths, which means if you do a local installation inside of a Vagrant instance, DCR will only be runnable from within the Vagrant instance.

Using relative paths will allow the use of DCR both in the HOST and the GUEST machines, making it more useful inside of a git hooks.

**Comment by Decipher** [comment]
As a workaround, I currently have the following configuration and custom post task (for Beetbox):

`.beetbox/config.yml`
```
dcr_standards: "../../drupal/coder/coder_sniffer,../../alexdesignworks/dcr/php_codesniffer,../../../.dcr"
```

`.beetbox/tasks/post/dcr.yml`
```
---

- name: Configure PHPCS standards for DCR.
  command: "vendor/bin/phpcs --config-set installed_paths {{ dcr_standards }} > /dev/null"
  args:
    chdir: "{{ beet_base }}"

- name: Configure PHPCBF standards for DCR.
  command: "vendor/bin/phpcbf --config-set installed_paths {{ dcr_standards }} > /dev/null"
  args:
    chdir: "{{ beet_base }}"
```

Also worth noting that DCR is being installed via `composer.json` in this case, rather than via the ansible role.
